version: '2'
services:
  database:
    image: postgres:9.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=amorphic
      - POSTGRES_PASSWORD=amorphic
      - POSTGRES_DB=myticketdb
    volumes:
      - ./.postgres:/var/lib/postgresql/data
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amorphic-ticket-demo:latest
    depends_on:
      - database
    ports:
      - '3000:3000'
    env_file:
      - ./demo.env
    environment:
      - application=ticket
    command: ./wait-for-it.sh database:5432 -- node app.js
  batch-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    image: amorphic-daemon-ticket-demo:latest
    depends_on:
      - database
    env_file:
      - ./demo.env
    environment:
      - application=batch
    command: ./wait-for-it.sh database:5432 -- node app.js
    
