version: '2'
services:
  redis:
    image: redis:4.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./.redis:/data
    #command: redis-server /tmp/redis.conf --appendonly yes
  database:
    image: postgres:9.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=amorphic
      - POSTGRES_PASSWORD=amorphic
      - POSTGRES_DB=dmyticketdb
    volumes:
      - ./.postgres:/var/lib/postgresql/data
  nginx:
    image: nginx:1.12
    ports:
      - '3001:80'
    environment:
      - UPSTREAM=ticket-demo:3000
  amorphic-ticket-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: amorphic-ticket-demo:latest
    depends_on:
      - database
      - redis
    ports:
      - '3000'
    env_file:
      - ./demo.env
    command: node app.js
    
